### ISSUE TITLE
Help users deal with MonadST now depending on PrimMonad

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/io-sim#146]
As of PR #141, it's no longer, for example, trivial to derive `MonadST` for a newtype monad.

- It'd be helpful if the Haddock on `MonadST` called out the dependence on `PrimMonad`, and ideally suggested how to workaround it. (If `PrimState` were a top-level family instead of associated, the `PrimMonad` instance wouldn't be required! Although, as Duncan mentioned in PR 141, `PrimMonad` does usefully enable the rest of the API from `primitive`.)

- Either add `withLiftST k = k stToIO` as a default, or at least spell it out in the Haddock.

- Etc?

**Comment by coot** [comment]
@nfrisby could you review #147.
