### ISSUE TITLE
io-classes-mtl-0.1.2.0 is not buildable on GHC 9.8.2

### ISSUE THREAD

**Issue by carbolymer** [input-output-hk/io-sim#164]
io-classes-mtl-0.1.2.0 is not buildable on GHC 9.8.2. See the attached [error.log](https://github.com/input-output-hk/io-sim/files/15483430/error.log).

Taken from: https://github.com/IntersectMBO/cardano-cli/actions/runs/9254721425/job/25457077489?pr=777#step:11:973

**Comment by bolt12** [comment]
This is a known bug which has been fix: https://github.com/input-output-hk/io-sim/pull/163. We'll try to release it asap

**Comment by uhbif19** [comment]
Reproduces on GHC 9.6.3.

**Comment by bolt12** [comment]
There was a revision made today, could you please make sure it is fixed now and then close the issue? cc @carbolymer @uhbif19

**Comment by carbolymer** [comment]
Testing in https://github.com/IntersectMBO/cardano-node/pull/5869

**Comment by carbolymer** [comment]
@bolt12 seems to be working, thanks!

**Comment by uhbif19** [comment]
Works for me too.
