### ISSUE TITLE
fused-effects + GenServer + LinearType + IOSim = COOL!!

### ISSUE THREAD

**Issue by EMQ-YangM** [input-output-hk/io-sim#5]
https://github.com/EMQ-YangM/fused-effects-process/blob/master/src/Control/Effect/T.hs

io-sim is very useful. Thanks for making such a useful thing.

**Comment by coot** [comment]
Thanks a lot @EMQ-YangM for letting us know that you find `io-sim` useful.  We cannot live without it ;)
