### ISSUE TITLE
Failed assertion when running ThreadNet tests, using v0.4

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/io-sim#94]
`ouroboros-consensus` tests fail when enabling assertion, using version `0.4`. The [following assertion](https://github.com/input-output-hk/io-sim/blob/7ba9a3e1339a43946cbc1e44cfa0ad0e4748582c/io-sim/src/Control/Monad/IOSim/Internal.hs#L172) is triggered.

See [the full log](https://cicero.ci.iog.io/api/run/log/a8b231f2-2c1e-f86a-8e5c-33b7951c7562/nomad?raw&strip-ansi).

**Comment by coot** [comment]
Could you attach simulation trace?

You'd need to use `traverse_ print (Data.List.Trace.toList trace)` to print it as `ppTrace_` will evaluate it and throw an exception before returning a string.

**Comment by dnadales** [comment]
As this is not blocking any other work, I'd say we have to check if this is still an issue in the latest version. What do you think?

**Comment by coot** [comment]
sure, if you cannot reproduce it with the same salt then it's fixed.  Is this test using `threadDelay` or `timeout`?

**Comment by dnadales** [comment]
I don't know. I'd have to check :)

**Comment by coot** [comment]
Please re-open if this is still an issue.
